### ISSUE TITLE
ISE lab: user1 is disabled

### ISSUE THREAD

**Issue by drnop** [CiscoDevNet/devnet-express-security-issues#14]
user1 used in the ISE lab has been automatically disabled by ISE. (ISE default is to disable users after X days..). Maybe we can fix this in next dCloud version, or add to lab guide.

**Comment by annegentle** [comment]
Let me know if the fix is accurate in https://learninglabs.cisco.com/lab/intro-to-ISE-ANC-Policy-APIs/step/2. I added to the note, "After a default period of time, ISE will disable the user, so check the current status before starting your work in the simulator." Thanks for reporting.
