### ISSUE TITLE
Move the Missions back with the associated Modules

### ISSUE THREAD

**Issue by cmlccie** [CiscoDevNet/devnet-express-security-issues#15]
While it was a grand experiment in trying something new, after running the first 11 or so events, the consensus of the SPOT team is that it would be better to have participants complete the mission associated with each module at the end of the module.

## Reasons

- The modules (and the event) lose some participant engagement and enthusiasm by doing *only* the listen and learn portions of our `Listen > Learn > Put It Into Practice` model for **most** of the event.
- Participants are often eager to wrap-up the second day, and either leave early or rush through the missions.
- The event *gamification* isn't effective with all of the awards happening in a short and abbreviate period at the end of the event.
- Doing the mission at the end of the module will help the participants solidify what they have learned, while it is still fresh (we have seen the effectiveness of this pattern in the other tracks).

## Summary

We are a good portion of the proven impact of the `Listen > Learn > Put It Into Practice` by delaying the *Put It Into Practice* step.

## Additional Ideas

There is merit in showing a connected process; how these APIs can and should work in tight coordination as part of a digitized workflow.  Perhaps we could have an optional / extra-challenge *Workflow Mission* available for participants to tackle on their own at the end of the event.  Perhaps we could leave their PoDs active for an additional day and challenge participants to complete it "for bragging rights" with the workflow mission posting something cool to the event Webex Teams space!

Perhaps we could leverage CTR's emerging APIs and have the *Workflow Mission* be a threat hunting mission.

**Comment by cmlccie** [comment]
I have asked the SPOT team members to share any strong opinions on this topic with me and suggested that we would wait until after the break to begin implementing this change.

So far, all of the strong opinions have been in favor of move the missions back with the modules.

**Comment by RuthCattell** [comment]
This issue is to be discussed when we have the 'post-Security track release' call so we can agree on a way forward.

**Comment by annegentle** [comment]
In the 1/10/19 call we agreed to move missions with associated modules.

**Comment by klevenstein** [comment]
Resolved in v1.1
