### ISSUE TITLE
PowerPoint Presentation does not match Lab Content

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/devnet-express-security-issues#2]
On the Slide deck for module “REST API Fundamentals” there is a Section for LAB 3 “Hands On Exercise: Using Postman to Interact with REST APIs” it talks about Restconf and the output from a router. While the lab guide talks about deckofcards

**Comment by annegentle** [comment]
The router output example is an example only - not intended for hands-on. Is there a way to make that clear, perhaps in the Notes section of the slides?

**Comment by annegentle** [comment]
@veeratcisco I think you are going to change the slides to avoid using a router example. Can you give an update on where this is?

**Comment by veeratcisco** [comment]
fixed in new verison
