### ISSUE TITLE
threat grid lab step 3 needs to have specific date filter in request

### ISSUE THREAD

**Issue by chrivand** [CiscoDevNet/devnet-express-security-issues#22]
https://learninglabs.cisco.com/tracks/devnet-express-security/threatgrid/intro-to-threat-grid-api/step/3

https://panacea.threatgrid.com/api/v2/iocs/feeds/domains?domain=Insert-the-domain-from-above-here&api_key={}

What is the samples ID of the sample with the time stamp on that was submitted the 2018-08-04 ?

**Comment by chrivand** [comment]
it should be this: url = 'https://panacea.threatgrid.com/api/v2/iocs/feeds/domains?after=2018-07-18T21:39:13Z&before=2019-07-18T22:39:13Z&domain=lamp.troublerifle.bid&api_key={}'.format(api_key)

**Comment by JeMunos** [comment]
solution code and lab example code should be updated now.
