### ISSUE TITLE
confusing that is pointed to other lab without link

### ISSUE THREAD

**Issue by chrivand** [CiscoDevNet/devnet-express-security-issues#23]
Switch to intro-to-ISE-ANC-Policy-APIs learning lab in this module and look for:

For ANC policy creation, please see Create an ISE ANC Policy

For ISE ANC policy creation, please see Create an ISE Authorization Policy.

https://learninglabs.cisco.com/tracks/devnet-express-security/ise/Hands-On-Exercise/step/1

**Comment by klevenstein** [comment]
Fixed in v1.1
