### ISSUE TITLE
umbrella enforcement mission says custkey, needs to be enforcement_key

### ISSUE THREAD

**Issue by chrivand** [CiscoDevNet/devnet-express-security-issues#25]

**Comment by chrivand** [comment]
hi Anne, this is just to be consequent throughout code. custkey is also not really describing what the variable is, so according to python best practices it is better to change it to enforcement_key

**Comment by annegentle** [comment]
And now I'm pretty sure I've walked into more work than I signed up for. :) @chrivand I think you and @veeratcisco are going to do a pass to match the Learning Lab text to the code. Or, can we figure out how to not update in two places?

**Comment by klevenstein** [comment]
Fixed in v1.1
