### ISSUE TITLE
Windows Python 3 activate virtual environment  - "Step 3: Setup Python Virtual Environment"

### ISSUE THREAD

**Issue by P0nt05** [CiscoDevNet/devnet-express-security-issues#26]
Hi,

on a Windows system there is no "source" command available, so you have to activate the python virtual env with a batch script.
See attached screens:
![2019-02-11_13-41-06](https://user-images.githubusercontent.com/41740851/52564298-1c3cbc00-2e04-11e9-958a-790799336e1d.png)

![2019-02-11_13-41-54](https://user-images.githubusercontent.com/41740851/52564313-265eba80-2e04-11e9-9791-87bb209d43b3.png)

**Comment by annegentle** [comment]
Hi - thanks for reporting. We intend for those instructions to be run in Git Bash. That said, we can also add the Windows command line instructions.
