### ISSUE TITLE
Exploring FMC Access Control Policies gives Request Exception: 400 Client Error: Bad Request for url:

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/devnet-express-security-issues#3]
Hands-On (Optional Advanced Exercise): Exploring FMC Access Control Policies and Modifying Policies with the FMC REST API

Step 3: Work with access control policies using helper functions

Instructions in this section need to be clarified. When you create an access policy using the FMC api explorer as instructed and then run the fmc_access_polict.py script you get this Request Exception error.

Created URL: https://198.18.133.9:443/api/fmc_config/v1/domain/e276abec-e0f2-11e3-8169-6d9ed49b625f/policy/accesspolicies
Sending POST request to https://198.18.133.9:443/api/fmc_config/v1/domain/e276abec-e0f2-11e3-8169-6d9ed49b625f/policy/accesspolicies
Request Exception: 400 Client Error: Bad Request for url: https://198.18.133.9:443/api/fmc_config/v1/domain/e276abec-e0f2-11e3-8169-6d9ed49b625f/policy/accesspolicies

Appears to be because the policy already exists from being created in the fmc api browser. Simply changing the name of the policy in the script fixes the problem. The script creates a new policy.

Lab instructions should be fixed to explain that if the policy already exists the script it will fail or possibly build in a check in the script to report that the policy exists.

We had several people in the Iselin event run into this problem.

**Comment by annegentle** [comment]
@veeratcisco Can you take a look and see how to clarify?

**Comment by veeratcisco** [comment]
This is an optional exercise meant for only advanced users. Most of them should be able to resolve policy exists issue... it's an important learning for objects exists...

We can note that in the learning lab, but this is not a production script and should not be used for it. Just learning the tool.

We'll do the enhancement

**Comment by klevenstein** [comment]
v1.1 rewrite should resolve this.
