### ISSUE TITLE
typo in amp step2.py

### ISSUE THREAD

**Issue by chrivand** [CiscoDevNet/devnet-express-security-issues#31]
found a typo in the guide
Walk through the step2.py code
section
If you are at devnet express hosted event you can replace {your api amp hostmane} with amp.dcloud.cisco.com
it says "hostmane" instead of "hostname"

**Comment by klevenstein** [comment]
Hi @chrivand - I'm having a hard time locating the file with this issue. Can you give me a link or point me in the correct direction?

**Comment by chrivand** [comment]
step 2: https://developer.cisco.com/learning/tracks/devnet-express-security/ampforendpoints/intro-into-amp-apis/step/2

**Comment by klevenstein** [comment]
Looks like there's a dne-security-amp-labs repo I don't have access to. @annegentle can you help?

**Comment by chrivand** [comment]
I can also fix these issues later. At airport now

**Comment by klevenstein** [comment]
Thanks! We just saw these come in and figured they'd be some low-hanging fruit to take care of.

**Comment by chrivand** [comment]
true, feel free to fix them when you are able to access the files :-)

**Comment by annegentle** [comment]
Ah, got it! Added Write access to https://github.com/CiscoDevNet/dne-security-amp-labs. ⚡️
