### ISSUE TITLE
Introduction to ISE ANC Policy APIs - Step 2.7 - Don't see user1 in Live Sessions

### ISSUE THREAD

**Issue by cmlccie** [CiscoDevNet/devnet-express-security-issues#33]
In [Step 2](https://developer.cisco.com/learning/tracks/devnet-express-security/ise/intro-to-ISE-ANC-Policy-APIs/step/2) after following all of the instructions up to this point, at step 2.7, where the instruction is:

"7. You should see the authenticated user1 session in ISE under **Operations->RADIUS->Live Sessions**"

***I don't see `user1`.***

I do see `user1` in step 2.8, under **Operations->RADIUS->Live Logs**

**Comment by veeratcisco** [comment]
This is known issue we provided the workaround notes in the lab
