### ISSUE TITLE
[v1.1] Answers to questions in Hands-On: Introduction to Cisco Threat Grid APIs step 3 not anymore correct

### ISSUE THREAD

**Issue by pcardotatgit** [CiscoDevNet/devnet-express-security-issues#41]
=>  Hands-On: Introduction to Cisco Threat Grid APIs 
  => step 3 : Query elements of a data sample 

I think that answers to questions are not anymore corrects

 Hints : Yes , 6 (as of 04-2018), 5cb84e5aaf5759066c43f5639d5a0508
![TG-3](https://user-images.githubusercontent.com/20640868/58615991-cf022e80-82bc-11e9-8d11-2aff2c0518ef.jpg)

**Comment by veeratcisco** [comment]
fixed.. Karin
