### ISSUE TITLE
[v1.1] Threat Grid Credentials needed in Hands-On: Introduction to Cisco Threat Grid APIs

### ISSUE THREAD

**Issue by pcardotatgit** [CiscoDevNet/devnet-express-security-issues#42]
=> Hands-On: Introduction to Cisco Threat Grid APIs
  => Step 3: Query elements of a data sample
    => Use the returned data for analysis
![TG-4](https://user-images.githubusercontent.com/20640868/58617123-a2034b00-82bf-11e9-9e9b-4b13397b8e77.jpg)

For reading  [ /samples/ID/analysis/artifacts API endpoint  ]  it is mentioned that we must connect to panacea.threatgrid.com.   But we need credentials  and we dont have it in the lab guide.

**Comment by veeratcisco** [comment]
fixed.
