### ISSUE TITLE
[v1.1] Comment - I needed to comment the MISSION variable in all mission scripts

### ISSUE THREAD

**Issue by pcardotatgit** [CiscoDevNet/devnet-express-security-issues#43]
More a comment than an Issue, but I think that attendees may come across the same as me and can be stuck on this.

For almost all mission scripts I had to comment the MISSION Variable to make scripts work 

#print missing mission warning!
#MISSION = print_missing_mission_warn()

If not doing this, even the script is correct, it keeps on returning : 

_Please replace 'MISSION' with correct required mission statements!

At hosted DNE Event; Please ask for help from procter or your neighbour attendee; if you are not making progress..._

Maybe it is worth it to add additional instructions regarding the MISSION variable

**Comment by veeratcisco** [comment]
fixed.
