### ISSUE TITLE
V1.1 ISE MISSION TODO's confusing

### ISSUE THREAD

**Issue by chrivand** [CiscoDevNet/devnet-express-security-issues#46]
#TODO: finish the URL for the GET request to get the ANC policy from ISE
url = f"https://{username}:{password}@{MISSION}"

<--- it is not clear that you also need to add the API endpoint so maybe like this (otherwise people thing everything should be in the curly brackets):

url = f"https://{username}:{password}@MISSION"

#TODO: finish the URL for the PUT request to apply the ANC policy!
url = f"{MISSION}.../ers/config/ancendpoint/apply"

<--- this should be changed to (otherwise people thing everything should be in the curly brackets):

url = f"MISSION/ers/config/ancendpoint/apply"

**Comment by veeratcisco** [comment]
fixed!
