### ISSUE TITLE
1.1 TG MISSION typos + camelCase

### ISSUE THREAD

**Issue by chrivand** [CiscoDevNet/devnet-express-security-issues#47]
In thgrid_mission.py
TODO: iterate trhough the shalist and find the obereravales per sha! hint: for ... in ...:
-> obereravales should be observables
-> findObervables should be findobservables (with an s and no capital o)
-> function name is camelCase 
-> trhough should be through

**Comment by annegentle** [comment]
These typos are in https://github.com/CiscoDevNet/dne-security-code/blob/master/intro-threatgrid/mission/thgrid_mission.py and not in a Learning Lab.

**Comment by klevenstein** [comment]
Just fixed one of the typos and it looks like the others are done as well; closing.
