### ISSUE TITLE
Investigate Key created for DevNet only allows GET requests not POST request

### ISSUE THREAD

**Issue by veeratcisco** [CiscoDevNet/devnet-express-security-issues#5]
Investigate Key created for DevNet only allows GET requests, not POST request. This impacts the Umbrella module.

**Comment by chrivand** [comment]
This has to do with the tier of the API, the key is then for Tier 1, which excludes the Bulk API endpoints. I have pointed this out to Jennifer Liou already multiple times.

Check section 3, table 4: https://www.cisco.com/c/en/us/products/collateral/security/umbrella/umbrella-og.html

**Comment by annegentle** [comment]
We've taken care of this by updating the instructions for obtaining a key. Closing.
