### ISSUE TITLE
1.1 TG artifacts API endpoint can only be found in the TG docs (but we don't have a login)

### ISSUE THREAD

**Issue by chrivand** [CiscoDevNet/devnet-express-security-issues#50]
the screenshot says "artifacts" in the URL, but it is not clear that it can be found there. During DNE participants cannot login to TG docs...

https://developer.cisco.com/learning/devnet-express/devnet-express-security-v1-1/ise-v11/intro-to-threat-grid-api-v-1-1/step/3

**Comment by veeratcisco** [comment]
Just learning lab change..

**Comment by veeratcisco** [comment]
fixed with note
