### ISSUE TITLE
No mention to switch to using postman in Documentation

### ISSUE THREAD

**Issue by GShuttleworth** [CiscoDevNet/devnet-express-security-issues#54]
This step ( https://developer.cisco.com/learning/devnet-express/devnet-express-security-v1-1/ise-v11/intro-to-ISE-ANC-Policy-APIs-v-1-1/step/5 ) requires users to use Postman, but this is not said anywhere. It is only deducible by looking at the screenshots.

**Comment by klevenstein** [comment]
Published.
