### ISSUE TITLE
Wrong directory in guide

### ISSUE THREAD

**Issue by securenetwrk** [CiscoDevNet/devnet-express-security-issues#8]
On https://learninglabs.cisco.com/tracks/devnet-express-security/intro-python/intro-python-part1/step/6 it says 

`Open ~/code/dnav3-code/intro-python/part1/hands_on_exercise.py in your editor.`

But the code folder is actually `dne-security-code` not `dnav3-code`.

**Comment by securenetwrk** [comment]
Also, it is probably a good idea to `grep -r dnav3 *` in the repo and find any other examples, particularly in the python section.

**Comment by annegentle** [comment]
Yeah, I fixed it in another MD file but will do again.

**Comment by annegentle** [comment]
Was able to get this completed and published - closing. Thanks for reporting!
